export const STATUS_PRESETS = [
	{
		id: "available",
		label: "Available",
		icon: "CheckCircle2",
		color: "emerald",
		badgeText: "Welcome",
		defaultSubText: "Please knock before entering.",
		glowClass: "shadow-emerald-500/20 border-emerald-500/30 bg-emerald-500/5",
		textClass: "text-emerald-400",
		bgGradient:
			"from-emerald-950/30 via-zinc-950 to-zinc-950 animate-pulse-slow",
	},
	{
		id: "meeting",
		label: "In a Meeting",
		icon: "Users",
		color: "amber",
		badgeText: "Do Not Disturb",
		defaultSubText: "Please do not disturb unless urgent.",
		glowClass: "shadow-amber-500/20 border-amber-500/30 bg-amber-500/5",
		textClass: "text-amber-400",
		bgGradient: "from-amber-950/30 via-zinc-950 to-zinc-950",
	},
	{
		id: "recording",
		label: "Video Recording",
		icon: "Video",
		color: "red",
		badgeText: "ON AIR",
		defaultSubText:
			"Screen or video recording in progress. Please keep noise to a minimum.",
		glowClass:
			"shadow-red-500/30 border-red-500/30 bg-red-500/5 animate-pulse-glow",
		textClass: "text-red-500",
		bgGradient: "from-red-950/45 via-zinc-950 to-zinc-950",
		hasPulse: true,
	},
	{
		id: "podcast",
		label: "Audio Recording",
		icon: "Mic",
		color: "purple",
		badgeText: "LIVE RECORDING",
		defaultSubText:
			"Audio recording in progress. Please keep noise to a minimum.",
		glowClass: "shadow-purple-500/35 border-purple-500/30 bg-purple-500/5",
		textClass: "text-purple-400",
		bgGradient: "from-purple-950/40 via-zinc-950 to-zinc-950",
		hasWaveform: true,
	},
	{
		id: "study",
		label: "Studying",
		icon: "BookOpen",
		color: "blue",
		badgeText: "Busy",
		defaultSubText: "Please do not disturb unless urgent.",
		glowClass: "shadow-blue-500/20 border-blue-500/30 bg-blue-500/5",
		textClass: "text-blue-400",
		bgGradient: "from-blue-950/30 via-zinc-950 to-zinc-950",
	},
	{
		id: "dnd",
		label: "Do Not Disturb",
		icon: "MinusCircle",
		color: "rose",
		badgeText: "Focus Mode",
		defaultSubText: "Please do not disturb unless urgent.",
		glowClass: "shadow-rose-500/30 border-rose-500/30 bg-rose-500/5",
		textClass: "text-rose-500",
		bgGradient: "from-rose-950/40 via-zinc-950 to-zinc-950",
	},
];
